name: Deploy

on:
  push:
  workflow_dispatch:

jobs:
  deploy:
    name: Verify PS outputs
    runs-on: ubuntu-latest
    steps:
      - name: Setting test Json output
        shell: pwsh
        id: json-set
        run: |
          $testOutput   = @{
            "TestName" = 'Foo';
            "SomeBool" = $false;
          }
          $json = ConvertTo-Json $testOutput -Compress
          echo "testJson=$json" >> $GITHUB_OUTPUT
      - name: Check test Json output
        shell: pwsh
        run: |
          echo "${{steps.json-set.outputs.testJson}}"
      - name: Run PS test
        uses: azure/powershell@v1
        id: json-set-ps
        with:
          inlineScript: |
            $params = ConvertFrom-Json -AsHashtable '${{steps.json-set.outputs.testJson}}'
            ./test.ps1 @params
      - name: Check PS output
        shell: pwsh
        id: json-set
        run: |
          echo "${{steps.json-set-ps.outputs.TestName}}"
            