name: Deploy

on:
  push:
  workflow_dispatch:

jobs:
  deploy:
    name: Verify PS outputs
    runs-on: ubuntu-latest
    steps:
      - name: Setting test Json output
        shell: bash
        id: json-set
        run: |
          exit 1
