name: Deploy

on:
  push:
  workflow_dispatch:

jobs:
  run-integration-tests:
    runs-on: ubuntu-latest
    name: Run tests
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Run tests
        uses: ./.github/actions/integration-tests
        with:
          working-directory: .
