name: Deploy

on:
  push:
  workflow_dispatch:

jobs:
  deploy:
    name: Verify PS outputs
    runs-on: ubuntu-latest
    steps:
      - name: Check that this errors
        shell: bash
        run: |
          echo "::group::Grouped output"
          & ls
          exit 1
          echo "::endgroup::"
      - name: Check that this also errors
        shell: bash
        run: |
          exit 1
